config/routes.rb
Yarn::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user, lambda { |user| user.admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  get 'users/me' => 'users#me'
  get 'profile' => 'users#profile'
  resources :users, only: %i(show)

  get 'subsumptions' => 'subsumptions#index', :as => :subsumptions

  namespace :subsumptions do
    post 'answer', :as => :answer
  end

  resource :relations_editor, controller: :relations_editor, only: %i[show destroy] do
    post :save
    get :relations
    get :next_example
  end

  resources :words do
    collection do
      get :approved
    end

    member do
      get :synsets
      get :synonyms
      get :raw_synonyms
      get :definitions
      get :raw_definitions
      get :examples
      get :raw_examples
    end

    member do
      get :approve
      get :disapprove
      get :history
      get :revert
    end
  end

  resources :definitions, only: [:index, :show] do
  end

  resources :examples, only: [:index, :show] do
  end

  resources :synset_words, only: [:show, :edit]

  resources :synsets, only: [:index, :show, :destroy, :edit] do
    resources :definitions, only: [:show]
    resources :words, controller: 'synset_words', only: [:show] do
      resources :samples, only: [:show]
    end

    collection do
      get :search
      post :merge
    end

    member do
      get  :approve
      post :set_domain
    end
  end

  resources :raw_synset_words, only: [:show]

  resources :raw_synsets, only: [:index, :show] do
    resources :words, controller: 'raw_synset_words', only: [:show] do
    end

    collection do
      get :search
    end
  end

  resources :posts

  get 'editor' => 'editor#index', :as => :editor

  namespace :editor do
    post 'search', :as => :search
    get 'definitions', :as => :definitions
    get 'synonymes', :as => :synonymes
    get 'append_word', :as => :append_word
    get 'append_definition', :as => :append_definition
    get 'word', :as => :word
    get 'next', :as => :next

    get 'ruscorpora_examples', :as => :ruscorpora_examples
    get 'opencorpora_examples', :as => :opencorpora_examples

    get 'show_synset', :as => :show_synset
    get 'sample', :as => :sample
    post 'set_default_definition', :as => :set_default_definition
    post 'set_default_synset_word', :as => :set_default_synset_word
    post 'create_synset', :as => :create_synset
    post 'update_definition', :as => :update_definition
    post 'create_sample', :as => :create_sample
    post 'edit_marks', :as => :edit_marks
    put 'save' => :save
  end

  root to: 'high_voltage/pages#show', id: 'index'
  get 'instructions' => redirect('/help')
  get 'content' => redirect('/data')
end

app/views/shared/_form_errors.html.erb
<% if f.object.errors.any? %>
  <h3>Возникшие ошибки</h3>
  <div class="alert alert-error">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <ul>
      <% f.object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_grants.html.erb
Проект выполняется при финансовой поддержке грантов <a href="http://www.rfh.ru">РГНФ</a> (РФФИ) №&nbsp;13-04-12020 «Новый открытый электронный тезаурус русского языка» и №&nbsp;16-04-12019 «Интеграция тезаурусов RussNet и YARN», а также в рамках научного проекта <a href="http://www.rfbr.ru/rffi/ru/">РФФИ</a> №&nbsp;16-37-00354 мол_а «Методы автоматизации процесса коллективного построения лингвистических ресурсов». Поддержка данного проекта осуществлена в рамках благотворительной деятельности, на средства, предоставленные <a href="http://www.prokhorovfund.ru/">Фондом Михаила Прохорова</a>.

app/views/shared/_metrika.html.erb
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter21358360 = new Ya.Metrika({id:21358360,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/21358360" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/shared/_navigation.html.erb
<ul class="nav nav-list">
  <%= active_link_to 'Главная страница', root_path, :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Новости', posts_path, :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Данные', page_path(:data), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Публикации', page_path(:publications), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Участники', page_path(:team), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Помощь', page_path(:help), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Конфиденциальность', page_path(:terms), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Технологии', page_path(:technologies), :wrap_tag => :li, :active => :exclusive %>
  <%= active_link_to 'Словник', words_path, :wrap_tag => :li, :active => :exclusive %>
  <% if current_user.try(:admin?) -%>
    <li class="divider"></li>
    <%= active_link_to 'Утверждённые слова', approved_words_path, :wrap_tag => :li %>
    <li><%= top_link_to('Слово №%d' % top_bar_word.id, word_url(top_bar_word)) if top_bar_word %></li>
    <li class="divider"></li>
    <%= active_link_to 'Синсеты', synsets_path, :wrap_tag => :li %>
    <li class="divider"></li>
    <li><%= top_link_to('Cинсет №%d' % top_bar_synset.id, synset_url(top_bar_synset)) if top_bar_synset %></li>
    <li><%= top_link_to('Cинсет-слово №%d' % top_bar_synset_word.id, synset_word_url(top_bar_synset, top_bar_synset_word)) if top_bar_synset_word %></li>
  <% end -%>
  <%= active_link_to 'Проект интеграции', page_path(:russnet), :wrap_tag => :li, :active => :exclusive %>
</ul>

app/views/shared/_search.html.erb
<form class="form-search" id="search" action="<%= words_path %>">
  <input type="text" class="input-medium search-query" name="q" placeholder="Введите слово">

  <button class="btn" type="submit" title="Искать">
    <i class="icon-search"></i>
  </button>
</form>

app/views/shared/_userbar.html.erb
<div id="userbar">
  <% if user_signed_in? %>
    <%= link_to profile_path, :title => 'Профиль' do %>
      <i class="icon icon-user"></i>&nbsp;<%= current_user %>
    <% end %>

    <%= link_to destroy_user_session_path, :method => :delete, :confirm => 'Завершить работу?' do %>
      <i class="icon icon-remove-circle"></i>&nbsp;Выйти
    <% end %>
  <% else %>
    <% unless Rails.env.production? %>
      <%= link_to 'Тестовый вход', user_omniauth_authorize_path(:developer,
        :origin => request.original_url) %>
    <% end %>

    <%= link_to user_omniauth_authorize_path(:github,
      :origin => request.original_url), :id => 'github-auth' do %>
      <i class="icon icon-user"></i>&nbsp;Войти при помощи GitHub
    <% end %>

    <%= link_to user_omniauth_authorize_path(:vkontakte,
      :origin => request.original_url), :id => 'vkontakte-auth' do %>
      <i class="icon icon-user"></i>&nbsp;Войти при помощи VK
    <% end %>

    <%= link_to user_omniauth_authorize_path(:facebook,
      :origin => request.original_url), :id => 'facebook-auth' do %>
      <i class="icon icon-user"></i>&nbsp;Войти при помощи Facebook
    <% end %>
  <% end %>
</div>

app/views/shared/_yarn_logo.html.erb
<h1 class="yarn-logo active"><%= link_to 'YARN', root_path, :class => 'no-underline' %></h1>