config/routes.rb
Yarn::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  authenticate :user, lambda { |user| user.admin? } do
    mount PgHero::Engine, at: 'pghero'
  end

  get 'users/me' => 'users#me'
  get 'profile' => 'users#profile'
  resources :users, only: %i(show)

  get 'subsumptions' => 'subsumptions#index', :as => :subsumptions

  namespace :subsumptions do
    post 'answer', :as => :answer
  end

  resource :relations_editor, controller: :relations_editor, only: %i[show destroy] do
    post :save
    get :relations
    get :next_example
  end

  resources :words do
    collection do
      get :approved
    end

    member do
      get :synsets
      get :synonyms
      get :raw_synonyms
      get :definitions
      get :raw_definitions
      get :examples
      get :raw_examples
    end

    member do
      get :approve
      get :disapprove
      get :history
      get :revert
    end
  end

  resources :definitions, only: [:index, :show] do
  end

  resources :examples, only: [:index, :show] do
  end

  resources :synset_words, only: [:show, :edit]

  resources :synsets, only: [:index, :show, :destroy, :edit] do
    resources :definitions, only: [:show]
    resources :words, controller: 'synset_words', only: [:show] do
      resources :samples, only: [:show]
    end

    collection do
      get :search
      post :merge
    end

    member do
      get  :approve
      post :set_domain
    end
  end

  resources :raw_synset_words, only: [:show]

  resources :raw_synsets, only: [:index, :show] do
    resources :words, controller: 'raw_synset_words', only: [:show] do
    end

    collection do
      get :search
    end
  end

  resources :posts

  get 'editor' => 'editor#index', :as => :editor

  namespace :editor do
    post 'search', :as => :search
    get 'definitions', :as => :definitions
    get 'synonymes', :as => :synonymes
    get 'append_word', :as => :append_word
    get 'append_definition', :as => :append_definition
    get 'word', :as => :word
    get 'next', :as => :next

    get 'ruscorpora_examples', :as => :ruscorpora_examples
    get 'opencorpora_examples', :as => :opencorpora_examples

    get 'show_synset', :as => :show_synset
    get 'sample', :as => :sample
    post 'set_default_definition', :as => :set_default_definition
    post 'set_default_synset_word', :as => :set_default_synset_word
    post 'create_synset', :as => :create_synset
    post 'update_definition', :as => :update_definition
    post 'create_sample', :as => :create_sample
    post 'edit_marks', :as => :edit_marks
    put 'save' => :save
  end

  root to: 'high_voltage/pages#show', id: 'index'
  get 'instructions' => redirect('/help')
  get 'content' => redirect('/data')
end

app/models/word.rb
# encoding: utf-8
class Word < ActiveRecord::Base
  self.table_name = 'current_words'

  include Yarn::Trackable::Head

  paginates_per 150

  attr_accessible :word, :grammar, :accents, :uris, :frequency

  belongs_to :author, class_name: 'User'
  belongs_to :approver, class_name: 'User'
  has_one :score, class_name: 'WordScore'

  has_many :old_words, -> { order 'revision DESC' }, :inverse_of => :origin

  has_many :synset_words
  has_many :raw_synset_words

  has_many :antonomy_relations
  has_many :word_relations

  has_many :synsets, :through => :synset_words
  has_many :definitions, :through => :synset_words
  has_many :examples, :through => :synset_words

  has_many :raw_synonym, :inverse_of => :word1, :foreign_key => :word1_id
  has_many :raw_synonyms, :through => :raw_synonym, :source => :word2

  has_many :raw_definitions
  has_many :raw_examples, :through => :raw_definitions

  scope :search, ->(query) {
    if (tokens = query.to_s.split).any?
      regexps = tokens.map { |w| Regexp.escape(w).gsub(/[ЕеЁё]/, '[ЕеЁё]') }
      bregexps = regexps.map { |r| "(word ~* '\\m%s')::integer" % r }
      select(['%s.*' % table_name, '%s AS rank' % bregexps.join(' + ')]).
      where(regexps.map { |r| "word ~* '%s'" % r }.join(' AND '))
    else
      where()
    end
  }

  scope :next_word, ->(id) {
    joins('JOIN (SELECT *, lead(id, 1) OVER (ORDER BY score DESC) AS next_word_id FROM current_words ' \
          'JOIN current_words_scores ON current_words_scores.word_id = current_words.id ' \
          'WHERE id = %1$d OR deleted_at IS NULL) AS ordered_words ON ordered_words.id = %1$d' % id).
    where('current_words.id = ordered_words.next_word_id').
    first
  }

  def update_from(new_word, save_method = :save)
    Word.transaction do
      old_words.last and
      old_words.last.created_at > 12.hours.ago and
      old_words.last.author_id == new_word.author_id or
      OldWord.from_word(self).save!

      self.word = new_word.word
      self.grammar = new_word.grammar
      self.accents = new_word.accents
      self.frequency = new_word.frequency
      self.uris = new_word.uris
      self.author_id = new_word.author_id
      self.approver_id = new_word.approver_id
      self.approved_at = new_word.approved_at
      self.revision += 1

      method(save_method).call.tap { |result| self.reload if result }
    end
  end  

  validates :word, presence: true
  validates_uniqueness_of :word, :scope => :grammar, if: ->(w) { w.new_record? }
  validates :grammar, presence: true

  def to_s
    word
  end

  def approved?
    approved_at && approver
  end

  def destroy
    update_with_tracking { |s| s.deleted_at = Time.now.utc }
  end
end

app/controllers/words_controller.rb
# encoding: utf-8

class WordsController < ApplicationController
  before_filter :authenticate_user!, only: %i(new create update approve disapprove revert destroy)
  before_filter :find_word, :except => [:index, :search, :approved, :new, :create]
  before_filter :set_top_bar_word, :except => [:index, :search, :approved]
  before_filter :prepare_revert, :only => :revert
  before_filter :track_word, :only => [:update, :revert]

  def index
    @words = WordsFinderService.new(params).find

    respond_to do |format|
      format.html
      format.xml { render xml: @words }
      format.json { render json: @words }
    end
  end

  def approved
    approver_id = Word.arel_table[:approver_id]
    approved_at = Word.arel_table[:approved_at]

    @words = Word.where(
      approver_id.not_eq(nil),
      approved_at.not_eq(nil)
    ).order(:word).page params[:page]

    respond_to do |format|
      format.html
      format.xml { render xml: @words }
      format.json { render json: @words }
    end
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(params[:word]) do |word|
      word.author = current_user
    end

    if @word.save
      flash[:notice] = 'Слово добавлено.'
      redirect_to word_url(@word)
    else
      flash[:alert] = 'Не получилось добавить слово.'
      render action: 'new'
    end
  end

  def show
    respond_to do |format|
      format.html
      format.xml { render xml: @word }
      format.json { render json: @word }
    end
  end

  def update
    params[:word].delete :approver_id
    params[:word].delete :approved_at

    if @word.update_from(@new_word)
      flash[:notice] = 'Слово обновлено.'
      redirect_to word_url(@word)
    else
      flash[:alert] = 'Не получилось обновить слово.'
      render action: 'edit'
    end
  end

  def synsets
    @synsets = @word.synsets.where(deleted_at: nil)

    respond_to do |format|
      format.xml { render xml: @synsets }
      format.json { render json: @synsets }
    end
  end

  def synonyms
    @synonyms = @word.synsets.includes(:lexemes).
      where(current_synsets: { deleted_at: nil },
            current_synset_words: { deleted_at: nil },
            current_words: { deleted_at: nil }).
      map(&:lexemes).flatten

    respond_to do |format|
      format.xml { render xml: @synonyms }
      format.json { render json: @synonyms }
    end
  end

  def raw_synonyms
    @synonyms = @word.raw_synonyms.where(deleted_at: nil)

    respond_to do |format|
      format.xml { render xml: @synonyms }
      format.json { render json: @synonyms }
    end
  end

  def definitions
    @definitions = @word.definitions.where(deleted_at: nil)

    respond_to do |format|
      format.xml { render xml: @definitions }
      format.json { render json: @definitions }
    end
  end

  def raw_definitions
    @definitions = @word.raw_definitions.includes(:definition).
      where(current_definitions: { deleted_at: nil }).
      map(&:definition)

    respond_to do |format|
      format.xml { render xml: @definitions }
      format.json { render json: @definitions }
    end
  end

  def examples
    @examples = @word.examples.where(deleted_at: nil)

    respond_to do |format|
      format.xml { render xml: @examples }
      format.json { render json: @examples }
    end
  end

  def raw_examples
    @examples = @word.raw_examples.includes(:example).
      where(current_examples: { deleted_at: nil }).
      map(&:example)

    respond_to do |format|
      format.xml { render xml: @examples }
      format.json { render json: @examples }
    end
  end

  def approve
    @word.approved_at = DateTime.now
    @word.approver = current_user

    if @word.save
      flash[:notice] = 'Версия была утверждена.'
    else
      flash[:alert] = 'Не удалось утвердить версию.'
    end

    redirect_to word_url(@word)
  end

  def disapprove
    @word.approved_at = @word.approver = nil

    if @word.save
      flash[:notice] = 'Утверждение версии снято.'
    else
      flash[:alert] = 'Не удалось снять утверждение версии.'
    end

    redirect_to word_url(@word)
  end

  def destroy
    if @word.destroy
      flash[:notice] = 'Слово удалено.'
    else
      flash[:alert] = 'Не удалось удалить слово.'
    end

    render json: []
  end

  def history
    @history = @word.old_words
  end

  def revert
    if @word.update_from(@new_word)
      flash[:notice] = 'Выполнен откат к предыдущей версии.'
    else
      flash[:alert] = 'Не получилось откатиться.'
    end

    redirect_to word_url(@word)
  end

  protected
  def find_word
    @word = Word.where(deleted_at: nil).find(params[:id])
  end

  def set_top_bar_word
    self.top_bar_word = @word
  end

  def prepare_revert
    word = OldWord.find_by_word_id_and_revision(@word, params[:revision])
    params[:word] = HashWithIndifferentAccess.new(word.attributes)
  end

  def track_word
    attributes = @word.attributes
    attributes.merge! params[:word]
    attributes['author_id'] = current_user.id
    @new_word = OpenStruct.new(attributes)
  end
end

app/helpers/words_helper.rb
# encoding: utf-8

module WordsHelper
  def title_word(word)
    raw "№#{@word.id}: &laquo;#{@word.word}&raquo;"
  end
end

app/views/words/_form.html.erb
<%= render 'shared/form_errors', :f => f %>
<div>
  <%= f.label :word, 'Слово:' %>
  <%= f.text_field :word %>
</div>
<div>
  <%= f.label :grammar, 'Склонение:' %>
  <%= f.text_field :grammar %>
</div>
<div>
  <%= f.label :frequency, 'Частота:' %>
  <%= f.text_field :frequency %>
</div>
<div>
  <%= f.submit 'Отправить', class: %w(btn btn-large) %>
</div>

app/views/words/_synsets.html.erb
<% if word.synset_words.size > 0 %>
  <h3>Связанные синсеты <span class="badge"><%= word.synset_words.size %></span></h3>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Синсет</th>
    </tr>

    <% word.synsets.where(deleted_at: nil).each do |synset| %>
      <tr>
        <td>
          <% if (words = synset_words(synset)).empty? %>
            <%= link_to synset.id, synset_path(synset) %>
          <% else %>
            <%= link_to synset.id, synset_path(synset) %>: <%= words %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p>Ещё нет ни одного связанного синсета.</p>
<% end %>

app/views/words/approved.html.erb
<%= heading_with_title "Утверждённые слова" %>

<% if @words.any? %>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Слово</th>
      <th>Утвердил</th>
      <th>Дата утверждения</th>
    </tr>

    <% @words.each do |word| %>
    <tr>
      <td><%= link_to word.word, word_path(word) %></td>
      <td><%= word.approver ? link_to(word.approver, '#') : 'н/д' %></td>
      <td><%= word.approved_at.strftime('%H:%M:%S %d.%m.%Y') rescue 'н/д' %></td>
    </tr>
    <% end %>
  </table>

  <%= paginate @words %>
<% else %>
  <p>Нет утверждённых слов.</p>
<% end %>

app/views/words/edit.html.erb
<%= heading_with_title raw "Редактирование слова #{title_word(@word)}" %>

<%= form_for @word do |f| %>
  <%= render 'form', f: f %>
<% end %>

<%= render_cell :entry, :metadata, entry: @word %>

app/views/words/history.html.erb
<%= heading_with_title raw "История изменений слова #{title_word(@word)}" %>

<% if @history.any? %>
  <table class="table table-bordered table-striped">
    <tr>
      <th>Версия</th>
      <th>Автор</th>
      <th>Дата</th>
      <th>Слово</th>
      <th>Утв.?</th>
      <th>Действие</th>
    </tr>

    <tr>
      <td><%= @word.revision %></td>
      <td><%= @word.author ? link_to(@word.author, '#') : 'н/д' %></td>
      <td><%= @word.updated_at.strftime('%H:%M:%S %d.%m.%Y') %></td>
      <td><%= @word %></td>
      <td><%= @word.approved? ? 'да' : 'нет' %></td>
      <td>(нет)</td>
    </tr>

    <tr>
      <% @history.each do |old_word| %>
        <td><%= old_word.revision %></td>
        <td><%= old_word.author ? link_to(old_word.author, '#') : 'н/д' %></td>
        <td><%= old_word.created_at.strftime('%H:%M:%S %d.%m.%Y') %></td>
        <td><%= old_word %></td>
        <td><%= old_word.approved? ? 'да' : 'нет' %></td>
        <td>
          <%= link_to 'Откатиться',
            revert_word_url(@word, revision: old_word.revision),
            class: %w(btn btn-small)
          %>
        </td>
      <% end %>
    </tr>
  </table>
<% else %>
  <p>Нет истории изменений.</p>
<% end %>

<%= render_cell :entry, :metadata, entry: @word %>
    

app/views/words/index.html.erb
<% if params[:q].present? %>
  <%= heading_with_title "Слова по запросу #{params[:q]}" %>
<% else %>
  <%= heading_with_title "Слова" %>
  <%= link_to 'Добавить слово', new_word_path %>
<% end %>

<% if @words.present? %>
  <ul class="triple-columns">
    <% @words.each do |word| %>
      <li><%= link_to word.word, word_path(word) %></li>
    <% end %>
  </ul>

  <%= paginate @words %>
<% else %>
  <p>Слова не найдены.</p>
<% end %>

app/views/words/new.html.erb
<%= heading_with_title raw 'Добавление нового слова' %>

<%= form_for @word do |f| %>
  <%= render 'form', f: f %>
<% end %>

app/views/words/show.html.erb
<%= heading_with_title raw "Слово #{title_word(@word)}" %>

<%= render 'words/synsets', :word => @word %>

<%= render_cell :entry, :metadata, entry: @word,
  edit_uri: edit_word_url(@word),
  approve_uri: approve_word_url(@word),
  disapprove_uri: disapprove_word_url(@word),
  history_uri: history_word_url(@word)
%>